name: "The Moltin Field Guide"
tagline: 'How to get on, work smart and make friends.'
version: 0.0.2

url: "http://moltin.github.io/field-guide"
baseurl: /

paginate: 10
permalink: pretty

# Github
githubLink: "https://github.com/moltin/field-guide"
